<a href="https://colab.research.google.com/github/TanatchaM/208499/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from scipy import stats
%matplotlib inline

# StatsModels
import statsmodels.api as sm
import statsmodels.formula.api as smf

# sklearnModels
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.svm import SVR
from sklearn.datasets import make_regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import RFE
from sklearn.linear_model import RidgeCV, LassoCV, Ridge, Lasso
from sklearn.datasets import load_boston

In [8]:
data = pd.read_csv('Data_Cleaning.csv')
df = pd.DataFrame(data)
df

Type_of_snake  Egg_age  mean_pulse_rate  Weight  Width  Eggscore
0    Corn_King_Milk       16            81.50    9.55  19.87         4
1    Corn_King_Milk       26            84.50   10.92  21.21         3
2    Corn_King_Milk       36            82.75   12.68  22.84         3
3    Corn_King_Milk       43            70.25   13.18  23.08         4
4    Corn_King_Milk       50            68.75   13.14  22.97         0
..              ...      ...              ...     ...    ...       ...
588         Hognose        7            72.75    8.77  21.52         3
589         Hognose       14            67.00    9.89  22.81         3
590         Hognose       21            69.50   10.13  23.88         3
591         Hognose       28            67.00   10.75  23.71         3
592         Hognose       35            82.50   11.12  24.97         3

[593 rows x 6 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 593 entries, 0 to 592
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Type_of_snake    593 non-null    object 
 1   Egg_age          593 non-null    int64  
 2   mean_pulse_rate  593 non-null    float64
 3   Weight           593 non-null    float64
 4   Width            593 non-null    float64
 5   Eggscore         593 non-null    int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 27.9+ KB


In [10]:
np.unique(df['Type_of_snake'])

array(['Corn_King_Milk', 'Hognose', 'Rat'], dtype=object)

In [11]:
df1 = df[df['Type_of_snake']=='corn_king_milk']
y = df['Egg_age'].to_numpy()
X = df.drop(['Egg_age', 'mean_pulse_rate', 'Eggscore', 'Type_of_snake'], axis=1).to_numpy()

In [12]:
scores = []
best_mlr = LinearRegression()
cv = KFold(n_splits=10, random_state=50, shuffle=False)
for train_index, test_index in cv.split(X,y):
    print("Train Index: ", train_index, "\n")
    print("Test Index: ", test_index)

    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    best_mlr.fit(X_train, y_train)
    scores.append(best_mlr.score(X_test, y_test))

Train Index:  [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149
 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203
 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221
 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239
 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257
 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275
 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293
 294 295 296 297 298 299 300 301 302 

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


In [13]:
print("LR coefficient is", best_mlr.coef_)
print("LR intercept is", best_mlr.intercept_)

LR coefficient is [-1.24646602  4.3070546 ]
LR intercept is -57.1925840754458


In [14]:
print(np.mean(scores))

0.1124849166743501


In [15]:
cross_val_score(best_mlr, X, y, cv=10)

array([ 0.28206726,  0.35085528,  0.09237285,  0.04684316,  0.28581607,
       -0.14199903,  0.15936881, -0.01371752,  0.04827178,  0.0149705 ])

In [16]:
cross_val_predict(best_mlr, X, y, cv=10)

array([15.61509545, 19.58398337, 24.31480146, 24.76148731, 24.36050748,
       17.75026164, 20.64960905, 29.86030255, 29.0769385 , 31.51286401,
       34.57017614, 25.14749283, 29.16022722, 30.70356401, 34.5007852 ,
       38.57175318, 40.69351095, 39.10525111, 23.41780856, 26.56251999,
       26.05290272, 31.07743341, 31.7212326 , 33.22796542, 24.06141201,
       25.02975333, 24.83029106, 31.00461696, 34.56430385, 36.15677217,
       37.76343187, 29.43544207, 29.4239911 , 30.92162187, 33.45346153,
       34.20501731, 34.46457272, 20.07069873, 24.09977768, 27.48035959,
       28.2463025 , 32.03422589, 31.79307034, 30.91594532, 32.75720318,
       23.08308779, 29.2250182 , 30.35572845, 36.67930849, 37.72301092,
       41.20332397, 41.88460797, 25.14406732, 30.00006316, 30.46368079,
       33.0590391 , 35.51806231, 33.82987559, 31.90777581, 25.66807171,
       30.86994751, 30.60459261, 37.09173746, 35.7773624 , 39.26132719,
       29.70935024, 34.47185277, 35.38269952, 39.11664912, 37.38

In [17]:
y_pred =  best_mlr.predict(X_test)
y_pred

array([39.74071224, 24.70416987, 29.06132096, 28.18867582, 30.51003919,
       31.24335001, 32.97974804, 28.986533  , 27.72883276, 28.66995344,
       31.30761727, 37.99982683, 22.19595552, 24.05759475, 25.25813131,
       25.08707958, 31.37216363, 30.6592171 , 30.1411401 , 31.05328335,
       32.30379747, 36.92850191, 37.06573209, 39.01069475, 29.20645076,
       32.956287  , 41.53570097, 39.78695719, 41.05092859, 45.46238443,
       30.65711296, 32.5343136 , 37.12730062, 35.66770493, 42.42434193,
       42.12864359, 21.24729198, 24.74080908, 29.31565487, 31.27443157,
       32.3637788 , 32.88173688, 26.24593622, 34.70280772, 40.33972944,
       43.23938897, 45.23111353, 48.28689924, 23.94541281, 27.92739364,
       34.09017307, 35.50939695, 37.05783246, 39.31909559, 24.56372402,
       28.72378252, 33.0331791 , 31.52817089, 36.49386726])

In [18]:
# importing r2_score module
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
# predicting the accuracy score
print("r2 score is", r2_score(y_test,y_pred))
print("MAE is", mean_absolute_error(y_test, y_pred))
print("MSE is", mean_squared_error(y_test,y_pred))
print("RMSE is", np.sqrt(mean_squared_error(y_test,y_pred)))

r2 score is 0.014970496118765997
MAE is 10.59898924031369
MSE is 161.68689115331304
RMSE is 12.715616035148004
